version: 2.1
jobs:
  build:
    docker: 
      - image: node:14-slim # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: Install dependencies for test
          command: |
            npm install jest ts-jest @types/jest
      - run:
          name: Run tests
          command: |
            npm run test
