version: 2.1
jobs:
  build:
    docker: 
      - image: node:14-slim # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: Run test
          command: |
            npm run test
